### ISSUE TITLE
Miner overwrites details about breaking update reproduction

### ISSUE THREAD

**Issue by gabrielskoglund** [chains-project/breaking-updates#45]
When running the miner, we sometimes overwrite the JSON data of previously found breaking updates. This is obviously a bug, and should not happen since we are supposed to only look for breaking updates that are _newer_ than the ones we have already found. This might possible be an issue with the timestamps of the last time we mined the repo.

**Comment by yogyagamage** [comment]
I'm looking into this.

**Comment by yogyagamage** [comment]
Initially the "createdAt" field in the JSON files was in the GMT time zone (https://github.com/chains-project/breaking-updates/commit/388bbf7bb93f27849f795a1ff64c77e5e545cac8) but later it was changed to the local time zone (https://github.com/chains-project/breaking-updates/commit/84c44de7bb5b6b98456897e1a8e0890f9a8476df). In all the rewritten JSON files in commit https://github.com/chains-project/breaking-updates/commit/2f2b42eb44f51686d9acf9760558a203b9f89d0c, the corresponding PR's created time was same as the "lastFetchedTime" (which was a bug). With the time gap between the two time zones, the next time when the PRs were fetched, "createdAt" timestamps became the newer timestamps, and the PRs were considered as not recorded, newly created PRs.

For example, the PR https://github.com/sakaiproject/sakai/pull/10914 was created at 2022-09-29 15:53:35 in GMT time zone and the "lastFetchedTime" was recorded exactly as 2022-09-29 15:53:35. Then the next time when time zone was changed, the timestamp of the PR creation was 2022-09-29 17:53:35 in local time, and was considered as a later timestamp than the "lastFetchedTime" which was 2022-09-29 15:53:35. Therefore, JSON file was overwritten.

As the time zone issue was fixed by https://github.com/chains-project/breaking-updates/pull/48, and the "lastFetchedTime" issue was fixed by https://github.com/chains-project/breaking-updates/commit/f67539fe250ab21d54359b82bb07139c3f8202af this will not happen again. 

However, there is an edge case when the "lastFetchedTime" is recorded exactly as the PRs "createdAt" time, the JSON files will be overwritten if it was already created. When considering the time required to fetch and record data, it is almost impossible to fetch a PR at the same moment it was created and record it with the same timestamp. 

Therefore, this issue can be closed.

**Comment by monperrus** [comment]
Thanks a lot for the thorough analysis @yogyagamage

**Comment by gabrielskoglund** [comment]
Thank you for the great detective work Yogya!
