### ISSUE TITLE
Create configuration files for GitHub tokens

### ISSUE THREAD

**Issue by frankreyesgarcia** [chains-project/breaking-updates#76]
It is necessary to create a new configuration file for GitHub tokens for each script, Find, Mine, Reproduce

**Comment by monperrus** [comment]
Maybe we should wait for more time, see https://github.com/chains-project/breaking-updates/blob/7cfb694b801500c361ee50085dd52aaa8a4e7145/src/main/java/miner/GitHubMiner.java#LL225C59-L225C63

**Comment by yogyagamage** [comment]
GitHub abuse limit timeout is increased to one minute in https://github.com/chains-project/breaking-updates/pull/87.  It is not necessary to wait for a longer time, as this will be reached only when a client sends too many requests in a short time span.

It is the GitHub rate limit (which is the allowed number of requests for each user or application per hour) that will be exceeded most of the time. Currently, it is handled by getting the rate limit reset time from the GitHub rate limit record and waiting until that reset time is reached (https://github.com/chains-project/breaking-updates/blob/7cfb694b801500c361ee50085dd52aaa8a4e7145/src/main/java/miner/GitHubMiner.java#LL222C0-L226C55). As far as I understand, that is correct and does not need to be changed. 

When we provide more than one token in the token queue, it is not a bug that the rate limit is reached at the same time for both tokens while mining repos. It happens because each API token is allocated to one thread.

As for the Find, Mine, and Reproduce processes, because we currently run separate commands, we already have the option to use different tokens when we pass the tokens file in each command. Therefore, in my opinion, we don't need to add any new config to use different tokens. @frankreyesgarcia what do you think?

**Comment by frankreyesgarcia** [comment]
Yes, it is possible to use different tokens for each command. This means that you would need to have a file with the tokens for each command you want to execute.

Having separate token files allows for more fine-grained control and flexibility in managing the execution of commands. You can easily update or modify the tokens for specific commands without affecting the tokens used for other commands. 

@yogyagamage 
If we use multiple tokens associated with the same GitHub account, would this not be a problem? Wouldn't GitHub detect that the same account is making too many requests with different tokens?
